/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * 사용자의 이메일 주소
     * @type {string}
     * @memberof ChangePasswordDto
     */
    email: string;
    /**
     * 사용자의 새로운 비밀번호
     * @type {string}
     * @memberof ChangePasswordDto
     */
    newPassword: string;
}

/**
 * Check if a given object implements the ChangePasswordDto interface.
 */
export function instanceOfChangePasswordDto(value: object): value is ChangePasswordDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function ChangePasswordDtoFromJSON(json: any): ChangePasswordDto {
    return ChangePasswordDtoFromJSONTyped(json, false);
}

export function ChangePasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'newPassword': json['newPassword'],
    };
}

export function ChangePasswordDtoToJSON(json: any): ChangePasswordDto {
    return ChangePasswordDtoToJSONTyped(json, false);
}

export function ChangePasswordDtoToJSONTyped(value?: ChangePasswordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'newPassword': value['newPassword'],
    };
}

