/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExampleDto } from './ExampleDto';
import {
    ExampleDtoFromJSON,
    ExampleDtoFromJSONTyped,
    ExampleDtoToJSON,
    ExampleDtoToJSONTyped,
} from './ExampleDto';

/**
 * 
 * @export
 * @interface CreateExpressionDto
 */
export interface CreateExpressionDto {
    /**
     * 
     * @type {string}
     * @memberof CreateExpressionDto
     */
    expression: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExpressionDto
     */
    meaning: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExpressionDto
     */
    usage: string;
    /**
     * 영어 예문과 한글 번역 배열 (최대 2개)
     * @type {Array<ExampleDto>}
     * @memberof CreateExpressionDto
     */
    examples: Array<ExampleDto>;
}

/**
 * Check if a given object implements the CreateExpressionDto interface.
 */
export function instanceOfCreateExpressionDto(value: object): value is CreateExpressionDto {
    if (!('expression' in value) || value['expression'] === undefined) return false;
    if (!('meaning' in value) || value['meaning'] === undefined) return false;
    if (!('usage' in value) || value['usage'] === undefined) return false;
    if (!('examples' in value) || value['examples'] === undefined) return false;
    return true;
}

export function CreateExpressionDtoFromJSON(json: any): CreateExpressionDto {
    return CreateExpressionDtoFromJSONTyped(json, false);
}

export function CreateExpressionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExpressionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'expression': json['expression'],
        'meaning': json['meaning'],
        'usage': json['usage'],
        'examples': ((json['examples'] as Array<any>).map(ExampleDtoFromJSON)),
    };
}

export function CreateExpressionDtoToJSON(json: any): CreateExpressionDto {
    return CreateExpressionDtoToJSONTyped(json, false);
}

export function CreateExpressionDtoToJSONTyped(value?: CreateExpressionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expression': value['expression'],
        'meaning': value['meaning'],
        'usage': value['usage'],
        'examples': ((value['examples'] as Array<any>).map(ExampleDtoToJSON)),
    };
}

