/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStudyDto
 */
export interface CreateStudyDto {
    /**
     * 스터디명
     * @type {string}
     * @memberof CreateStudyDto
     */
    title: string;
    /**
     * 스터디 진행 날짜
     * @type {Date}
     * @memberof CreateStudyDto
     */
    studiedAt: Date;
    /**
     * 스터디 설명
     * @type {string}
     * @memberof CreateStudyDto
     */
    description: string;
}

/**
 * Check if a given object implements the CreateStudyDto interface.
 */
export function instanceOfCreateStudyDto(value: object): value is CreateStudyDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('studiedAt' in value) || value['studiedAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateStudyDtoFromJSON(json: any): CreateStudyDto {
    return CreateStudyDtoFromJSONTyped(json, false);
}

export function CreateStudyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStudyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'studiedAt': (new Date(json['studiedAt'])),
        'description': json['description'],
    };
}

export function CreateStudyDtoToJSON(json: any): CreateStudyDto {
    return CreateStudyDtoToJSONTyped(json, false);
}

export function CreateStudyDtoToJSONTyped(value?: CreateStudyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'studiedAt': ((value['studiedAt']).toISOString()),
        'description': value['description'],
    };
}

