/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Scene } from './Scene';
import {
    SceneFromJSON,
    SceneFromJSONTyped,
    SceneToJSON,
    SceneToJSONTyped,
} from './Scene';

/**
 * 
 * @export
 * @interface ExtendedFilteredStudyDto
 */
export interface ExtendedFilteredStudyDto {
    /**
     * 아이디
     * @type {string}
     * @memberof ExtendedFilteredStudyDto
     */
    id: string;
    /**
     * 생성일
     * @type {Date}
     * @memberof ExtendedFilteredStudyDto
     */
    createdAt: Date;
    /**
     * 수정일
     * @type {Date}
     * @memberof ExtendedFilteredStudyDto
     */
    updatedAt: Date;
    /**
     * 삭제일
     * @type {Date}
     * @memberof ExtendedFilteredStudyDto
     */
    deletedAt: Date;
    /**
     * 스터디 진행 일자
     * @type {Date}
     * @memberof ExtendedFilteredStudyDto
     */
    studiedAt: Date;
    /**
     * 스터디 제목
     * @type {string}
     * @memberof ExtendedFilteredStudyDto
     */
    title: string;
    /**
     * 스터디 설명
     * @type {string}
     * @memberof ExtendedFilteredStudyDto
     */
    description: string;
    /**
     * 
     * @type {Scene}
     * @memberof ExtendedFilteredStudyDto
     */
    scene: Scene;
    /**
     * 스터디 신청자
     * @type {Array<User>}
     * @memberof ExtendedFilteredStudyDto
     */
    applicants?: Array<User>;
    /**
     * 스터디 참여자
     * @type {Array<User>}
     * @memberof ExtendedFilteredStudyDto
     */
    participants?: Array<User>;
    /**
     * 스터디 참여자 수
     * @type {number}
     * @memberof ExtendedFilteredStudyDto
     */
    participantCount: number;
    /**
     * 스터디 신청자 수
     * @type {number}
     * @memberof ExtendedFilteredStudyDto
     */
    applicantCount: number;
    /**
     * 스터디 진행 상황
     * @type {boolean}
     * @memberof ExtendedFilteredStudyDto
     */
    isCompleted: boolean;
}

/**
 * Check if a given object implements the ExtendedFilteredStudyDto interface.
 */
export function instanceOfExtendedFilteredStudyDto(value: object): value is ExtendedFilteredStudyDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('studiedAt' in value) || value['studiedAt'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('scene' in value) || value['scene'] === undefined) return false;
    if (!('participantCount' in value) || value['participantCount'] === undefined) return false;
    if (!('applicantCount' in value) || value['applicantCount'] === undefined) return false;
    if (!('isCompleted' in value) || value['isCompleted'] === undefined) return false;
    return true;
}

export function ExtendedFilteredStudyDtoFromJSON(json: any): ExtendedFilteredStudyDto {
    return ExtendedFilteredStudyDtoFromJSONTyped(json, false);
}

export function ExtendedFilteredStudyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedFilteredStudyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'deletedAt': (new Date(json['deletedAt'])),
        'studiedAt': (new Date(json['studiedAt'])),
        'title': json['title'],
        'description': json['description'],
        'scene': SceneFromJSON(json['scene']),
        'applicants': json['applicants'] == null ? undefined : ((json['applicants'] as Array<any>).map(UserFromJSON)),
        'participants': json['participants'] == null ? undefined : ((json['participants'] as Array<any>).map(UserFromJSON)),
        'participantCount': json['participantCount'],
        'applicantCount': json['applicantCount'],
        'isCompleted': json['isCompleted'],
    };
}

export function ExtendedFilteredStudyDtoToJSON(json: any): ExtendedFilteredStudyDto {
    return ExtendedFilteredStudyDtoToJSONTyped(json, false);
}

export function ExtendedFilteredStudyDtoToJSONTyped(value?: ExtendedFilteredStudyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
        'deletedAt': ((value['deletedAt']).toISOString()),
        'studiedAt': ((value['studiedAt']).toISOString()),
        'title': value['title'],
        'description': value['description'],
        'scene': SceneToJSON(value['scene']),
        'applicants': value['applicants'] == null ? undefined : ((value['applicants'] as Array<any>).map(UserToJSON)),
        'participants': value['participants'] == null ? undefined : ((value['participants'] as Array<any>).map(UserToJSON)),
        'participantCount': value['participantCount'],
        'applicantCount': value['applicantCount'],
        'isCompleted': value['isCompleted'],
    };
}

