/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationSceneDto } from './PaginationSceneDto';
import {
    PaginationSceneDtoFromJSON,
    PaginationSceneDtoFromJSONTyped,
    PaginationSceneDtoToJSON,
    PaginationSceneDtoToJSONTyped,
} from './PaginationSceneDto';

/**
 * 
 * @export
 * @interface PaginationSceneResponseDto
 */
export interface PaginationSceneResponseDto {
    /**
     * 전체 항목 수
     * @type {number}
     * @memberof PaginationSceneResponseDto
     */
    totalCount: number;
    /**
     * 현재 페이지 번호
     * @type {number}
     * @memberof PaginationSceneResponseDto
     */
    currentPage: number;
    /**
     * 응답 데이터 배열
     * @type {Array<PaginationSceneDto>}
     * @memberof PaginationSceneResponseDto
     */
    data: Array<PaginationSceneDto>;
}

/**
 * Check if a given object implements the PaginationSceneResponseDto interface.
 */
export function instanceOfPaginationSceneResponseDto(value: object): value is PaginationSceneResponseDto {
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaginationSceneResponseDtoFromJSON(json: any): PaginationSceneResponseDto {
    return PaginationSceneResponseDtoFromJSONTyped(json, false);
}

export function PaginationSceneResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationSceneResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'],
        'currentPage': json['currentPage'],
        'data': ((json['data'] as Array<any>).map(PaginationSceneDtoFromJSON)),
    };
}

export function PaginationSceneResponseDtoToJSON(json: any): PaginationSceneResponseDto {
    return PaginationSceneResponseDtoToJSONTyped(json, false);
}

export function PaginationSceneResponseDtoToJSONTyped(value?: PaginationSceneResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'currentPage': value['currentPage'],
        'data': ((value['data'] as Array<any>).map(PaginationSceneDtoToJSON)),
    };
}

