/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Scene
 */
export interface Scene {
    /**
     * 
     * @type {string}
     * @memberof Scene
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof Scene
     */
    studiedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Scene
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Scene
     */
    audioUrl: string;
}

/**
 * Check if a given object implements the Scene interface.
 */
export function instanceOfScene(value: object): value is Scene {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('studiedAt' in value) || value['studiedAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('audioUrl' in value) || value['audioUrl'] === undefined) return false;
    return true;
}

export function SceneFromJSON(json: any): Scene {
    return SceneFromJSONTyped(json, false);
}

export function SceneFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scene {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'studiedAt': (new Date(json['studiedAt'])),
        'description': json['description'],
        'audioUrl': json['audioUrl'],
    };
}

export function SceneToJSON(json: any): Scene {
    return SceneToJSONTyped(json, false);
}

export function SceneToJSONTyped(value?: Scene | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'studiedAt': ((value['studiedAt']).toISOString()),
        'description': value['description'],
        'audioUrl': value['audioUrl'],
    };
}

