/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEmailDto
 */
export interface SendEmailDto {
    /**
     * 인증 요청을 보낼 사용자의 이메일 주소
     * @type {string}
     * @memberof SendEmailDto
     */
    email: string;
}

/**
 * Check if a given object implements the SendEmailDto interface.
 */
export function instanceOfSendEmailDto(value: object): value is SendEmailDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function SendEmailDtoFromJSON(json: any): SendEmailDto {
    return SendEmailDtoFromJSONTyped(json, false);
}

export function SendEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEmailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function SendEmailDtoToJSON(json: any): SendEmailDto {
    return SendEmailDtoToJSONTyped(json, false);
}

export function SendEmailDtoToJSONTyped(value?: SendEmailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

