/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Scene } from './Scene';
import {
    SceneFromJSON,
    SceneFromJSONTyped,
    SceneToJSON,
    SceneToJSONTyped,
} from './Scene';

/**
 * 
 * @export
 * @interface Study
 */
export interface Study {
    /**
     * 
     * @type {Scene}
     * @memberof Study
     */
    scene: Scene;
    /**
     * 스터디 신청자
     * @type {Array<object>}
     * @memberof Study
     */
    applicants: Array<object>;
    /**
     * 스터디 참여자
     * @type {Array<object>}
     * @memberof Study
     */
    participants: Array<object>;
}

/**
 * Check if a given object implements the Study interface.
 */
export function instanceOfStudy(value: object): value is Study {
    if (!('scene' in value) || value['scene'] === undefined) return false;
    if (!('applicants' in value) || value['applicants'] === undefined) return false;
    if (!('participants' in value) || value['participants'] === undefined) return false;
    return true;
}

export function StudyFromJSON(json: any): Study {
    return StudyFromJSONTyped(json, false);
}

export function StudyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Study {
    if (json == null) {
        return json;
    }
    return {
        
        'scene': SceneFromJSON(json['scene']),
        'applicants': json['applicants'],
        'participants': json['participants'],
    };
}

export function StudyToJSON(json: any): Study {
    return StudyToJSONTyped(json, false);
}

export function StudyToJSONTyped(value?: Study | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scene': SceneToJSON(value['scene']),
        'applicants': value['applicants'],
        'participants': value['participants'],
    };
}

