/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMovieImageDto
 */
export interface UpdateMovieImageDto {
    /**
     * 영화 이미지 주소
     * @type {string}
     * @memberof UpdateMovieImageDto
     */
    imageUrl: string;
}

/**
 * Check if a given object implements the UpdateMovieImageDto interface.
 */
export function instanceOfUpdateMovieImageDto(value: object): value is UpdateMovieImageDto {
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function UpdateMovieImageDtoFromJSON(json: any): UpdateMovieImageDto {
    return UpdateMovieImageDtoFromJSONTyped(json, false);
}

export function UpdateMovieImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMovieImageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['imageUrl'],
    };
}

export function UpdateMovieImageDtoToJSON(json: any): UpdateMovieImageDto {
    return UpdateMovieImageDtoToJSONTyped(json, false);
}

export function UpdateMovieImageDtoToJSONTyped(value?: UpdateMovieImageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageUrl': value['imageUrl'],
    };
}

