/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSpeakerDto
 */
export interface UpdateSpeakerDto {
    /**
     * The name of the speaker
     * @type {string}
     * @memberof UpdateSpeakerDto
     */
    speakerName?: string;
    /**
     * The type of the speaker (e.g., A, B, etc.)
     * @type {string}
     * @memberof UpdateSpeakerDto
     */
    speakerType?: string;
}

/**
 * Check if a given object implements the UpdateSpeakerDto interface.
 */
export function instanceOfUpdateSpeakerDto(value: object): value is UpdateSpeakerDto {
    return true;
}

export function UpdateSpeakerDtoFromJSON(json: any): UpdateSpeakerDto {
    return UpdateSpeakerDtoFromJSONTyped(json, false);
}

export function UpdateSpeakerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSpeakerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'speakerName': json['speaker_name'] == null ? undefined : json['speaker_name'],
        'speakerType': json['speaker_type'] == null ? undefined : json['speaker_type'],
    };
}

export function UpdateSpeakerDtoToJSON(json: any): UpdateSpeakerDto {
    return UpdateSpeakerDtoToJSONTyped(json, false);
}

export function UpdateSpeakerDtoToJSONTyped(value?: UpdateSpeakerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'speaker_name': value['speakerName'],
        'speaker_type': value['speakerType'],
    };
}

