/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSceneDto
 */
export interface UpdateSceneDto {
    /**
     * Scene의 제목
     * @type {string}
     * @memberof UpdateSceneDto
     */
    title?: string;
    /**
     * 장면의 오디오 URL
     * @type {string}
     * @memberof UpdateSceneDto
     */
    audioUrl?: string;
    /**
     * Scene의 설명
     * @type {string}
     * @memberof UpdateSceneDto
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateSceneDto interface.
 */
export function instanceOfUpdateSceneDto(value: object): value is UpdateSceneDto {
    return true;
}

export function UpdateSceneDtoFromJSON(json: any): UpdateSceneDto {
    return UpdateSceneDtoFromJSONTyped(json, false);
}

export function UpdateSceneDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSceneDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'audioUrl': json['audioUrl'] == null ? undefined : json['audioUrl'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateSceneDtoToJSON(json: any): UpdateSceneDto {
    return UpdateSceneDtoToJSONTyped(json, false);
}

export function UpdateSceneDtoToJSONTyped(value?: UpdateSceneDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'audioUrl': value['audioUrl'],
        'description': value['description'],
    };
}

