/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExampleDto
 */
export interface ExampleDto {
  /**
   *
   * @type {string}
   * @memberof ExampleDto
   */
  en: string;
  /**
   *
   * @type {string}
   * @memberof ExampleDto
   */
  ko: string;
}

/**
 * Check if a given object implements the ExampleDto interface.
 */
export function instanceOfExampleDto(value: object): value is ExampleDto {
  if (!('en' in value) || value['en'] === undefined) return false;
  if (!('ko' in value) || value['ko'] === undefined) return false;
  return true;
}

export function ExampleDtoFromJSON(json: any): ExampleDto {
  return ExampleDtoFromJSONTyped(json, false);
}

export function ExampleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExampleDto {
  if (json == null) {
    return json;
  }
  return {
    en: json['en'],
    ko: json['ko'],
  };
}

export function ExampleDtoToJSON(json: any): ExampleDto {
  return ExampleDtoToJSONTyped(json, false);
}

export function ExampleDtoToJSONTyped(
  value?: ExampleDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    en: value['en'],
    ko: value['ko'],
  };
}
