/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Movie } from "./Movie";
import { MovieFromJSON, MovieFromJSONTyped, MovieToJSON, MovieToJSONTyped } from "./Movie";

/**
 *
 * @export
 * @interface PaginationMovieResponseDto
 */
export interface PaginationMovieResponseDto {
  /**
   * 전체 항목 수
   * @type {number}
   * @memberof PaginationMovieResponseDto
   */
  totalCount: number;
  /**
   * 현재 페이지 번호
   * @type {number}
   * @memberof PaginationMovieResponseDto
   */
  currentPage: number;
  /**
   * 페이지당 항목 수
   * @type {number}
   * @memberof PaginationMovieResponseDto
   */
  limit: number;
  /**
   * 응답 데이터 배열
   * @type {Array<Movie>}
   * @memberof PaginationMovieResponseDto
   */
  data: Array<Movie>;
}

/**
 * Check if a given object implements the PaginationMovieResponseDto interface.
 */
export function instanceOfPaginationMovieResponseDto(
  value: object,
): value is PaginationMovieResponseDto {
  if (!("totalCount" in value) || value["totalCount"] === undefined) return false;
  if (!("currentPage" in value) || value["currentPage"] === undefined) return false;
  if (!("limit" in value) || value["limit"] === undefined) return false;
  if (!("data" in value) || value["data"] === undefined) return false;
  return true;
}

export function PaginationMovieResponseDtoFromJSON(json: any): PaginationMovieResponseDto {
  return PaginationMovieResponseDtoFromJSONTyped(json, false);
}

export function PaginationMovieResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginationMovieResponseDto {
  if (json == null) {
    return json;
  }
  return {
    totalCount: json["totalCount"],
    currentPage: json["currentPage"],
    limit: json["limit"],
    data: (json["data"] as Array<any>).map(MovieFromJSON),
  };
}

export function PaginationMovieResponseDtoToJSON(json: any): PaginationMovieResponseDto {
  return PaginationMovieResponseDtoToJSONTyped(json, false);
}

export function PaginationMovieResponseDtoToJSONTyped(
  value?: PaginationMovieResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    totalCount: value["totalCount"],
    currentPage: value["currentPage"],
    limit: value["limit"],
    data: (value["data"] as Array<any>).map(MovieToJSON),
  };
}
