/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PublicUserDto
 */
export interface PublicUserDto {
  /**
   * 아이디
   * @type {string}
   * @memberof PublicUserDto
   */
  id: string;
  /**
   * 생성일
   * @type {Date}
   * @memberof PublicUserDto
   */
  createdAt: Date;
  /**
   * 수정일
   * @type {Date}
   * @memberof PublicUserDto
   */
  updatedAt: Date;
  /**
   * 삭제일
   * @type {Date}
   * @memberof PublicUserDto
   */
  deletedAt: Date;
  /**
   * 소셜 계정 플랫폼
   * @type {string}
   * @memberof PublicUserDto
   */
  provider: string;
  /**
   * 이메일
   * @type {string}
   * @memberof PublicUserDto
   */
  email: string;
  /**
   * 닉네임
   * @type {string}
   * @memberof PublicUserDto
   */
  nickname: string;
}

/**
 * Check if a given object implements the PublicUserDto interface.
 */
export function instanceOfPublicUserDto(value: object): value is PublicUserDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
  if (!('provider' in value) || value['provider'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('nickname' in value) || value['nickname'] === undefined) return false;
  return true;
}

export function PublicUserDtoFromJSON(json: any): PublicUserDto {
  return PublicUserDtoFromJSONTyped(json, false);
}

export function PublicUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicUserDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
    deletedAt: new Date(json['deletedAt']),
    provider: json['provider'],
    email: json['email'],
    nickname: json['nickname'],
  };
}

export function PublicUserDtoToJSON(json: any): PublicUserDto {
  return PublicUserDtoToJSONTyped(json, false);
}

export function PublicUserDtoToJSONTyped(
  value?: PublicUserDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
    deletedAt: value['deletedAt'].toISOString(),
    provider: value['provider'],
    email: value['email'],
    nickname: value['nickname'],
  };
}
