/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TokensDto
 */
export interface TokensDto {
  /**
   * 사용자의 액세스 토큰
   * @type {string}
   * @memberof TokensDto
   */
  accessToken: string;
  /**
   * 사용자의 리프레시 토큰
   * @type {string}
   * @memberof TokensDto
   */
  refreshToken: string;
}

/**
 * Check if a given object implements the TokensDto interface.
 */
export function instanceOfTokensDto(value: object): value is TokensDto {
  if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
  if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
  return true;
}

export function TokensDtoFromJSON(json: any): TokensDto {
  return TokensDtoFromJSONTyped(json, false);
}

export function TokensDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokensDto {
  if (json == null) {
    return json;
  }
  return {
    accessToken: json['accessToken'],
    refreshToken: json['refreshToken'],
  };
}

export function TokensDtoToJSON(json: any): TokensDto {
  return TokensDtoToJSONTyped(json, false);
}

export function TokensDtoToJSONTyped(
  value?: TokensDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    accessToken: value['accessToken'],
    refreshToken: value['refreshToken'],
  };
}
