/* tslint:disable */
/* eslint-disable */
/**
 * Renglish API Swagger
 * Download: <a href=/api-docs-ahyeon-renglish-api/swagger-json target=\"_blank\">click here</a><br/><br/>github: <a href=\"https://github.com/ahyeon-jung/renglish\" target=\"_blank\">ahyeon-jung/renglish</a><br/>contact: ahyeon.aisha@gmail.com
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateDialogueDto
 */
export interface UpdateDialogueDto {
  /**
   * 영어 대사
   * @type {string}
   * @memberof UpdateDialogueDto
   */
  englishScript?: string;
  /**
   * 한국어 대사
   * @type {string}
   * @memberof UpdateDialogueDto
   */
  koreanScript?: string;
  /**
   *
   * @type {number}
   * @memberof UpdateDialogueDto
   */
  order?: number;
}

/**
 * Check if a given object implements the UpdateDialogueDto interface.
 */
export function instanceOfUpdateDialogueDto(value: object): value is UpdateDialogueDto {
  return true;
}

export function UpdateDialogueDtoFromJSON(json: any): UpdateDialogueDto {
  return UpdateDialogueDtoFromJSONTyped(json, false);
}

export function UpdateDialogueDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateDialogueDto {
  if (json == null) {
    return json;
  }
  return {
    englishScript: json["english_script"] == null ? undefined : json["english_script"],
    koreanScript: json["korean_script"] == null ? undefined : json["korean_script"],
    order: json["order"] == null ? undefined : json["order"],
  };
}

export function UpdateDialogueDtoToJSON(json: any): UpdateDialogueDto {
  return UpdateDialogueDtoToJSONTyped(json, false);
}

export function UpdateDialogueDtoToJSONTyped(
  value?: UpdateDialogueDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    english_script: value["englishScript"],
    korean_script: value["koreanScript"],
    order: value["order"],
  };
}
