export const TAG = {
  TOKEN_REQUIRED: "[TOKEN]",
  ADMIN_REQUIRED: "[ADMIN]",
  STUDY_APPLICANT_REQUIRED: "[STUDY APPLICANT]",
  STUDY_PARTICIPANT_REQUIRED: "[STUDY PARTICIPANT]",
  EMAIL_VERIFICATION_REQUIRED: "[EMAIL VERIFICATION]",
};
