import "../styles/globals.css";

import Header from "@/components/Header";
import type { Metadata } from "next";
import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "REnglish",
  description: "Generated by create next app",
};

type LayoutProps = {
  components: React.ReactNode;
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Nav />
      </body>
    </html>
  );
}
