services:
  renglish_nginx:
    image: nginx:stable-alpine
    container_name: renglish_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - renglish_backend
    networks:
      - renglish-network

  renglish_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: renglish_backend
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - "7070:7070"
    depends_on:
      - renglish_db
    networks:
      - renglish-network

  renglish_db:
    container_name: renglish_db
    image: postgres:latest
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - renglish-network

networks:
  renglish-network:
    driver: bridge
