name: Auto Assign Assignee

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
    types: [opened, reopened, edited]
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to yourself
        if: github.event_name == 'pull_request'
        run: |
          echo "Assigning PR to ahyeon-jung..."
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.APP_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"assignees":["ahyeon-jung"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}"

      - name: Assign Issue to yourself
        if: github.event_name == 'issues'
        run: |
          echo "Assigning issue to ahyeon-jung..."
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.APP_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"assignees":["ahyeon-jung"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"

