name: Auto Assign Assignee and Admin Label

on:
  pull_request:
    branches:
      - 'main'

jobs:
  assign-reviewers-and-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assign PR to yourself
        run: |
          curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.APP_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"assignees":["a-honey"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}"
